name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  Build-Test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: npm Build-Test
        run: npm test
  Deploy:
    runs-on: ubuntu-22.04
    needs: [Build-Test]
    steps:
      - uses: actions/checkout@v3
      - if: ${{ github.event_name == 'push' }}
        name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "peaceful-depths-73716"
          heroku_email: "davidjumiller@gmail.com"
          healthcheck: "https://peaceful-depths-73716.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
